import Head from 'next/head'
import { useState, useEffect } from 'react'
import Button from '../components/Button'
import Github from '../components/Icons/Github'
import { logInWithGithub, onAuthStateChanged } from '../firebase/client'
import styles from '../styles/style'


export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChanged(setUser)
  }, [])
  

  const handleClick = () => {
    logInWithGithub()
    .then(user => {
      const { avatarURL, username} = user;
      console.log(user)
      setUser(user);
    })
    .catch(error => console.log(error))
  }
  return (
    <div>
      <Head>
        <title>DevTer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="">DevTer!</a>
        </h1>
        { user === null ? <Button onClick={handleClick}>
          <Github fill='white'/>
            Login with github
          </Button> :
          <div>
            <span>{user.username}</span>
          </div>
        }
      </main>
      <style jsx global>{styles}</style>
    </div>
  )
}
